package com.supermarket.pos.service;

import com.supermarket.pos.dao.SaleDAO;
import com.supermarket.pos.model.CartItem;
import com.supermarket.pos.model.Sale;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;

/**
 * SalesService - Business logic for sales transactions.
 * Handles completing sales, calculating profits, and recording transactions.
 */
public class SalesService {

    /**
     * Complete a sale from the current cart
     * @return Sale ID generated by database
     * @throws SQLException if database operation fails
     */
    public static int completeSale() throws SQLException {
        if (CartService.isCartEmpty()) {
            throw new IllegalArgumentException("Cart is empty. Cannot complete sale.");
        }

        // Create new sale
        Sale sale = new Sale();
        sale.setDatetime(LocalDateTime.now());
        sale.setItems(CartService.getCart());
        sale.setTotalAmount(CartService.calculateTotal());
        sale.setTotalProfit(CartService.calculateProfit());

        // Save to database
        int saleId = SaleDAO.addSale(sale);

        // Update inventory for each item
        for (CartItem item : sale.getItems()) {
            int newQuantity = item.getProduct().getQuantity() - item.getQuantity();
            item.getProduct().setQuantity(newQuantity);
            InventoryService.updateProduct(item.getProduct());
        }

        return saleId;
    }

    /**
     * Calculate profit for a sale
     * @param sale Sale object
     * @return Profit amount
     */
    public static double calculateProfit(Sale sale) {
        if (sale == null || sale.getItems().isEmpty()) {
            return 0.0;
        }

        double profit = 0.0;
        for (CartItem item : sale.getItems()) {
            double itemSelling = item.getSubtotal();
            double itemCost = item.getProduct().getPurchasePrice() * item.getQuantity();
            profit += (itemSelling - itemCost);
        }
        return profit;
    }

    /**
     * Get sale by ID
     * @param saleId Sale ID
     * @return Sale object or null if not found
     * @throws SQLException if database operation fails
     */
    public static Sale getSaleById(int saleId) throws SQLException {
        return SaleDAO.getSaleById(saleId);
    }

    /**
     * Get all sales
     * @return List of sales
     * @throws SQLException if database operation fails
     */
    public static List<Sale> getAllSales() throws SQLException {
        return SaleDAO.getAllSales();
    }

    /**
     * Get sales within date range
     * @param startDate Start date (format: YYYY-MM-DD)
     * @param endDate End date (format: YYYY-MM-DD)
     * @return List of sales within range
     * @throws SQLException if database operation fails
     */
    public static List<Sale> getSalesByDateRange(String startDate, String endDate) throws SQLException {
        if (startDate == null || startDate.trim().isEmpty()) {
            throw new IllegalArgumentException("Start date cannot be empty");
        }
        if (endDate == null || endDate.trim().isEmpty()) {
            throw new IllegalArgumentException("End date cannot be empty");
        }
        return SaleDAO.getSalesByDateRange(startDate, endDate);
    }

    /**
     * Delete a sale by ID
     * @param saleId Sale ID to delete
     * @throws SQLException if database operation fails
     */
    public static void deleteSale(int saleId) throws SQLException {
        if (saleId <= 0) {
            throw new IllegalArgumentException("Invalid sale ID");
        }
        SaleDAO.deleteSale(saleId);
    }
}
